name: 'docs'

on:
  push:
      branches: [main]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: tdene/btd@v1
      with:
        token: ${{ github.token }}
