name: 'docs'

on:
  push:
      branches: [main]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install pandoc
      run: |
          sudo apt install pandoc
    - uses: actions/checkout@v2
    - uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}
